/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    Rating: typeof import('primevue/rating')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
